# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (every day at 00:00h)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
    - name: base
      if: ${{ success() || failure() }} 
      uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.METRICS_TOKEN }}
        filename: base.svg
        user: rafa-carmo
        template: classic
        base_indepth: yes
  
        config_display: large
        config_timezone: America/Sao_Paulo
        config_animations: yes

        repositories_affiliations: owner, collaborator
        commits_authoring: Rafael do Carmo, rafa-carmo, rafa-carmo@users.noreply.github.com

        plugin_lines: yes
        plugin_lines_history_limit: 3

        base: header, activity, metadata, community, metrics

    - name: General
      if: ${{ success() || failure() }}
      uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.METRICS_TOKEN }}
        filename: general.svg
        user: rafa-carmo
        template: classic
        
        base: ""
        config_display: large
        config_timezone: America/Sao_Paulo
        config_animations: yes
          
        config_order: languages, notable, discussions, topics, wakatime, isocalendar
        plugin_languages_details: lines, bytes-size, percentage
        
        repositories_affiliations: owner, collaborator
        commits_authoring: Rafael do Carmo, rafa-carmo, rafa-carmo@users.noreply.github.com
        
        plugin_isocalendar: yes
        plugin_notable: yes
        
        plugin_lines: yes
        plugin_lines_history_limit: 3

        plugin_traffic: yes
        
        plugin_languages: yes
        plugin_languages_ignored: scss, css, html, qml, perl, lua, ruby, objective-c++, jupyter notebook, mdx, markdown, yml
        plugin_languages_analysis_timeout: 60
        plugin_languages_analysis_timeout_repositories: 15
        plugin_languages_categories: programming
        plugin_languages_colors: github
        plugin_languages_limit: 10
        plugin_languages_recent_categories: markup, programming
        plugin_languages_recent_days: 30
        plugin_languages_recent_load: 1000
        plugin_languages_sections: most-used

        plugin_wakatime: yes
        plugin_wakatime_sections: time, languages, languages-graphs, editors, os
        plugin_wakatime_days: 365
        plugin_wakatime_languages_ignored: scss, css, html, qml, perl, lua, ruby, objective-c++, jupyter notebook, mdx, markdown
        plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

        plugin_music: yes
        plugin_music_playlist: https://music.youtube.com/playlist?list=PL9npxhyObI5LSdDrlfY3fhlvK_yf_Zx2c
        # plugin_music_provider: spotify